### ISSUE TITLE
ハイパーリンク属性を扱える hlground, ground のメンテナンス

### ISSUE THREAD

**Issue by nikosai** [lmntal/slim#206]
@alimjanyasin の功績である #40, feature/ground (b645adf) をマージする

**Comment by k-ueda** [comment]
目下作業中．諸事情で上記のオリジナルブランチは feature/ground-orig に改名し，拡張 ground の実装のC++への移植はfeature/extended-ground で作業中です．現在の feature/ground はその準備工事版（拡張機能は未導入だが新たな中間命令を読み込める），feature/extended-ground-orig は feature/ground-orig の（たぶん）旧版です．
