### ISSUE TITLE
dumperの改善

### ISSUE THREAD

**Issue by nikosai** [lmntal/slim#207]
LMNtalコード `X=[1,2,3|X].` をSLIMに渡すと、 `'.'(1,[2,3|L0],L0).` とprintされる。
これを改善したい。

**Comment by nikosai** [comment]
膜が絡む例では、
`root({a},{b})` は `root({a. },{b. }).` となるが、
`root({a(X)},{b(X)})` は `root(L0,L2). {+L2. b(L1). }, {+L0. a(L1). }.` となってしまう。
（これは難しいかも？）

**Comment by sano-jin** [comment]
# `X=[1,2,3|X]`などについて

1. 第一引数から順に今の戦略で（できるだけ括弧内に埋め込むように略記して）ダンプして
2. 最終引数がすでに出力済みのアトムへ接続されている場合，またはルールにおける自由リンクであった場合に
3. 今ダンプしているアトムがトップレベルのアトムであったら，
4. 最終引数のリンクをコネクタ（=）を用いた略記法で外に出すようにする

と言った方針を考えました．
トップレベルのシンボルアトムは，`dump_symbol_atom`に

```cpp
if (call_depth == 0) {
    port_put_raw_s(port, " >>>this is a toplevel atom<<< ");
}
```

を挟むと検知できます（`dump_top_level_atom`はなんか思ったよりもたくさん呼び出されているようだった）．

リンク先のアトムがすでに出力済みかどうかは，`dump_arg`ないの if 文と同じように`hashtbl_contains(&rec->args, i)`のようにすれば検知できると思います．

しかし，「最終引数を（コネクタと共に）前に持ってくる」というのは，前から順にポートへ出力していっている以上，困難かもしれません．．．

**Comment by sano-jin** [comment]
# `X=[1,2,3|X]` などについて

最終引数を前に持ってこなければ，簡単にできると思われる．
つまり，`[1,2,3|X] = X` のように表示するということ．

トップレベル（term の根）に cons アトムがあった場合は，必ずこのようにしてしまうのが楽かも知れない．

**Comment by sano-jin** [comment]
`[1,2,3|X] = X` のようにする pull-request
https://github.com/lmntal/slim/pull/273
を出しました．

**Comment by nikosai** [comment]
closed by #273
