### ISSUE TITLE
通常実行における実行順序を変更するオプション

### ISSUE THREAD

**Issue by nikosai** [lmntal/slim#215]
現在、SLIMの通常実行では “偶然” ルールを上から順に適用していくようになっている。
この順序を制御できるようなオプションが作れないだろうか？

ちなみに旧Java処理系時代にはシャッフル実行モードというのがあったらしい。
`-s1`, `-s2`, `-s3` といったオプションをつけると、適用可能なルールをランダムな順序で適用するようになる。
旧処理系ベースで動作しているUNYOでは今も `-s3` などのオプションが使えるので、試してみると良い。

**Comment by Tamu7532** [comment]
#252 で通常実行時におけるルールの実行順序についてのシャッフルオプションは実装しました。（--shuffle-rule）
各ルール内におけるマッチング順序のシャッフルはまだ実装してません（依然上からマッチングしていると思います）

**Comment by Tamu7532** [comment]
#252 で通常実行時に各ルール内でのマッチング順序をシャッフルするオプションを付けました（--shuffle-atom)
それと、--shuffle-ruleと--shuffle-atomを--shuffleオプションで同時に走らせるようにしています。

**Comment by nikosai** [comment]
closed by #252
