### ISSUE TITLE
ハイパーリンクが絡んだルールの生成

### ISSUE THREAD

**Issue by bluedragon1** [lmntal/slim#22]
# 現象

ハイパーリンクが関係したルールを他のルールで生成すると、生成されたルールが適用されない

```
init.
init :- n(!I),a,
(ntom @@ n(!A):-m(!A),m(!A)),(atob @@ a:-b).
ntok @@ n(!A):-k(!A).
```

もとからあるルール(ntok)は適用されるが、生成されたルール(ntom)は適用されない。
ちなみにもう一つ生成されたルール(atob)は適用される

**Comment by ayhsmt97** [comment]
現行の SLIM でも同様に、ntom ルールが適用されない現象を確認しました
```
$ slim --hl --nd -t 22test.lmn
States
1::{init. @4. }
2::{a. n(!H21). @4. @5. }
3::{a. k(!H20). @4. @5. }
4::{b. n(!H21). @4. @5. }
5::{b. k(!H21). @4. @5. }

Transitions
init:1
1::2
2::3,4
3::5
4::5
5::

'# of States'(stored)   = 5.
'# of States'(end)      = 1.
```

**Comment by mishina-haruto** [comment]
ルールが(...)で囲まれている場合に実はうまくパースができていなかった．
そのルール内にハイパーリンクが出てこないときは偶然うまくいっていたが，ハイパーリンクを使うと問題が露呈していた．
lmntal.cupのUnitAtomを修正することで改善した．
