### ISSUE TITLE
zerostep使用時に膜を外そうとする命令を行うとsegmentation faultを起こす

### ISSUE THREAD

**Issue by Tamu7532** [lmntal/slim#233]
`{a}.
{'$callback'(zerostep).
{a}:-a.
}.`
のように, 膜を外そう（消そう）とする命令について,zerostep実行の処理を行うと実行時にsegmentation faultになる.

補足として, 
`{a}:-{b}.`
`{a}:-{{a}},{b}.`
など膜の中身を変更したり膜を増やしたりする命令は正常に動く.

**Comment by Tamu7532** [comment]
> /**
> * @brief 0stepルールセットを登録するためのコールバック
> *
> * @details
> *   膜の中に入っているルールセットを0stepルールセットとする。
> *   そのルールセットを親膜に移動し、元々の膜を削除する。
> *   ただし、callback命令が終わった際、'$callback'アトムがdeleteされるため、
> *   膜のメモリを解放してしまうとメモリアクセス違反が起きる。
> *   現状ではメモリを解放せず親膜からの削除だけ行う。（これはメモリリークになる）
> * @todo
> *   メモリアクセス違反が起きないように膜のメモリを解放できるような仕様にする。
> */

詳細がzerostep.cppに記載してありました

**Comment by k-ueda** [comment]
プロセス文脈を移動するルールは（膜の再利用ができていないため）動かないようです．
```
{'$callback'(zerostep).
promote@@ {$q}, {$p} :- {$q,$p}, {}.
}.
{a,b},{c,d,e}.
```
zerostep.cppのコメント中の「膜」は，'$callback' アトムを囲む膜のことで，zerostep実行するルール左辺の膜ではないように読めますがどうでしょう？

**Comment by icecocoa6** [comment]
バグの直接の原因はzerostepルールが初期状態を作るinitial rulesetと共に動作した時、初期化されていない膜スタックにアクセスしようとしてメモリアクセス違反を起こしていることでした。ですので、膜スタックにアクセスする際にReactCxtが膜指向実行モードかどうか検査するように修正いたしました。

**Comment by icecocoa6** [comment]
initial rulesetはtask.cpp:432の`react_start_rulesets`で実行されます。
```cpp
void react_start_rulesets(LmnMembraneRef mem, Vector *rulesets) {
  LmnReactCxt rc(REACT_STAND_ALONE);
  int i;

  RC_SET_GROOT_MEM(&rc, mem);

  for (i = 0; i < rulesets->get_num(); i++) {
    react_ruleset(&rc, mem, (LmnRuleSetRef)rulesets->get(i));
  }
  react_initial_rulesets(&rc, mem);
  react_zerostep_recursive(&rc, mem);

#ifdef USE_FIRSTCLASS_RULE
  // register first-class rulesets produced by the initial process.
  lmn_rc_execute_insertion_events(&rc);
#endif
}
```
ここで確保されているReactCxtは`REACT_STAND_ALONE`（≠膜指向実行モード）で初期化されているため、膜スタックが確保されません。
`REACT_STAND_ALONE`はここ以外で使われていないので、このコードが正しいかどうかはわかりませんが、ともかく#234で修正した部分には実行モードを検査する部分が抜けていたので追加いたしました。

**Comment by icecocoa6** [comment]
ちなみに、@k-ueda先生が挙げられているコードはzerostepで実行すると無限ループになります。zerostep ruleは「停止するまでzerostep ruleを適当に適用する」という動作を行うためです。

zerostepは勢いで実装したため、この辺りの動作というか、意味論はあまりよろしくないと思います……。速度向上のためのツールとして実験的に提供されているので、zerostepを使った場合理論的にはモデル検査の健全性も完全性も保証されません。

**Comment by k-ueda** [comment]
早速の対応ありがとう．私の上記のコードは，元のプログラム（LaViT同梱のλ計算からβ簡約以外を隠蔽した版）から怪しい部分を抽出したものなので，上記のコード自体が無限ループするのは承知しています．
zerostepを使った場合の完全性は一般に保証されないけど，健全性については，どのようなプログラムでどのような意味でunsoundでしょうか？
完全性についても「どのような場合には保証されるか」（十分条件）を示すほうが前向きです．機能の位置づけとしてはzerostepはPromelaのd_stepなどと近いです．
zerostepは利用者も増えてきたので，公開ドキュメントにもそろそろ掲載したいです．本当は構文も整備したいですが，とりあえず機能の提供が優先なので．

**Comment by icecocoa6** [comment]
> zerostepを使った場合の完全性は一般に保証されないけど，健全性については，どのようなプログラムでどのような意味でunsoundでしょうか？

zerostepは本来生成される状態を省略して停止状態まで飛ばしてしまうので、zerostepを使わない場合に本来生成されるはずだった状態に検証条件を満たすようなものがあった場合には健全性が失われます。つまり、zerostep適用前ではLTLモデル検査で検出できた性質をzerostep適用後では検出できなくなります。どういう状況のときに起こり得るかというと、省略される状態でのみ真偽が変わる原子論理式を検査しているときなどがありえます。
省略される状態からあるいは省略される状態への遷移があるときも健全性が失われる可能性もありますが、私が非決定実行時の挙動をどう実装したのか思い出せないのであまり確証はありません。

> 完全性についても「どのような場合には保証されるか」（十分条件）を示すほうが前向きです．機能の位置づけとしてはzerostepはPromelaのd_stepなどと近いです．

直感的にいえば、「モデル検査の検証条件とzerostep ruleが関係ない場合」ですね。たとえばよくあるのは、シミュレーションを開始する前にモデルを生成する処理などです。形式的に証明するのは少々骨が折れそうですが、zerostepで省略される状態の原始論理式の値が全て同じとか、ループがあるかないかとか……検証条件によってはもっと強いことが言えることがあると思います。

**Comment by k-ueda** [comment]
テストしたのですが，次のプログラムが非決定実行では正しく動くようですが通常実行でSegmentation Faultします．
`beta@@ H=apply(lambda(A, B), C) :- H=B, A=C.

{'$callback'(zerostep).
l_c@@  lambda(A,B)=cp(C,D,L), {+L,$q} :-
         C=lambda(E,F), D=lambda(G,H), A=cp(E,G,L1), B=cp(F,H,L2),
         {{+L1},+L2,sub(S)}, {super(S),$q}.
a_c@@  apply(A,B)=cp(C,D,L), {+L,$q} :-
         C= apply(E,F), D= apply(G,H), A=cp(E,G,L1), B=cp(F,H,L2),
         {+L1,+L2,$q}.

c_c1@@ cp(A,B,L1)=cp(C,D,L2), {{+L1,$p},+L2,$q} :- A=C, B=D, {{$p},$q}.
c_c2@@ cp(A,B,L1)=cp(C,D,L2), {{+L1,$p},$q}, {+L2,top,$r}
          :- C=cp(E,F,L3), D=cp(G,H,L4), {{+L3,+L4,$p},$q},
             A=cp(E,G,L5), B=cp(F,H,L6), {+L5,+L6,top,$r}.
c2c@@  A=cp(B,C) :- A=cp(B,C,L), {+L,top}.

promote@@ {{},$p,sub(S)}, {$q,super(S)} :- {$p,$q}.
gc@@   {top} :- {del}.
}.

N=n(2) :- N=lambda(cp(F0,F1), lambda(X, apply(F0,apply(F1,X)))).
r=apply(n(2), n(2)).
`
`0: r(apply(n(2),n(2))). @4. @5. 
---->_Nn2N
1: r(apply(lambda(cp(L1,L2,{top. }),lambda(L3,apply(L1,apply(L2,L3)))),n(2))). @4. @5. 
---->beta
2: r(lambda(L1,apply(L2,apply(L3,L1)))). n(2,cp(L2,L3,{top. })). @4. @5. 
---->_Nn2N
3: r(lambda(L2,apply(lambda(cp(L3,L4,L0),lambda(L5,apply(L3,apply(L4,L5)))),apply(lambda(cp(L6,L7,L1),lambda(L8,apply(L6,apply(L7,L8)))),L2)))). {top. +L0. +L1. }, {del. }. @4. @5. 
Segmentation fault (コアダンプ)
`
これもpromoteルールではないかと思います．

**Comment by icecocoa6** [comment]
こちらも原因としては膜スタックでした。zerostep中に膜を作ったり消したりすると膜スタックに残ったまま膜が解放されてしまうようです。
膜の作成／解放を全て追うのはあまり現実的ではないので、zerostepが一通り終わったら膜スタックを一から作り直すことにしました。処理的には多少不利ですが、一般的なプログラムにおける膜の数を考えれば許容範囲だと思います。また、この方法でも最適化の余地はあるので処理効率が問題になったときに修正することは可能です。

#234 にコミットしておきました。

**Comment by nikosai** [comment]
最適化の余地ありとのことですが、表題の問題は解決しているので、ひとまずこのIssueはcloseします。
