### ISSUE TITLE
状態数に関する問題

### ISSUE THREAD

**Issue by adachi-r** [lmntal/slim#243]
非決定実行を行う際、Tree Compression非適用時の場合実際よりも多く状態数が出力されてしまう。
例：phi_13.il(ベンチマークセットに同梱)：適用時が7297、非適用時が27437となる
現在、コミット番号59d5fa759d9fcadc1a678d252b0cb78cbc9209c7(2020/6/17)まで同様の現象を確認済み
なお、上記の1つ前のコミットからstate_dumper関連のエラーを出力してmakeで失敗してしまうことが判明した

コミット番号3f52f6809c2741e4135a1fd6850c33c0fc7b1834(2019/7/15)では正常に動作している
その次のコミット番号37aee1d4d16dfcb8f88a048f23eeae4620094479においてlmn_mem_free_recが宣言されていない旨のエラーを出力し、その後のコミット番号bea51edb14dd2926c8af6b28382a93b4b832dbc4でstate_dumper関連のエラーを出力している。

どうやら--hlオプションを適用すると正常に動作することが判明
恐らく--ndにバグあり?

PhilosopherとLeader Electionで状態数バグが発生している模様
同型性判定が正常に機能していない?

**Comment by nikosai** [comment]
以下のシンプルなプログラムでも問題が再現することを確認しました。
```
a(a(a(a(a(a(a(a(a(L)))))))),L).
a(X,Y) :- b(X,Y).
```
なお、同様のプログラムでaの数を8以下にすると再現せず、9以上でのみ問題が発生します。

# To reproduce
上記プログラムを `test.lmn` として、
```
slim --nd --hl test.lmn
```
で実行すると全状態数が60（正常）と表示されるが、
```
slim --nd test.lmn
```
の場合は64と異常値が表示される。

**Comment by nikosai** [comment]
問題が最初に発生したコミット： a1751611

**Comment by sano-jin** [comment]
上記の「問題が最初に発生したコミット： `a175161`」から，`--mem-enc`オプションも正しく動作しなくなる．

具体的には
```
a(a(a(a(a(a(a(a(a(L)))))))),L).
a(X,Y) :- b(X,Y).
```
の状態数が「257」（正常なら 60）と出る．

一つ遡って，`1e739bc`でテストすると，これは正常に動作した（`--mem-enc`オプションをつけて，状態数は 60 と出た）．

**Comment by sano-jin** [comment]
ちなみに`--mem-enc`オプションをつけて状態数がおかしくなる最小（ぽい）プログラムは以下です．
```
a(a(a(L)), L).
a(X, Y) :- b(X, Y).
```
これは，
- `--mem-enc`をつけると，状態数が5
- `--mem-enc`をつけないと，`--hl`をつけたのもつけないのも，状態数が4
となります．

**Comment by nikosai** [comment]
fixed by #254
