### ISSUE TITLE
system_ruleset のルール名の表示がわかりにくい

### ISSUE THREAD

**Issue by sano-jin** [lmntal/slim#274]
# system_ruleset のルール名の表示がわかりにくい

## 背景
現在，「system_ruleset」
https://github.com/lmntal/slim/blob/develop/lib/system_ruleset.lmn
のルール名は（明示的にルール名を書いていないために，コンパイラによって補われ） `HABi` のように表示される．

が，これは分かりにくいので，（特に不都合などが出てこない限り）ルール名を `ルール名 @@` のように明示的に書くべきだと思う．

## 改善例
例えば，
```
H='+'(A, B) :- int(A),int(B),A+B=C | H=C.
```
は

```
add@@ H='+'(A, B) :- int(A),int(B),A+B=C | H=C.
```
のようにするべき．

## 補足
ルール名の命名規則はもっと拘っても良いかも知れない．
`system_plus` とか？
けど，いづれにせよ，ルール名がちゃんと書いてあった方が良いと思う．

## 方法
特にコード規約みたいのが明示的にあるわけではない（たぶん）ので適当で良い．
けど，一般的には以下のフローに従うと思う．

0. クローンしてきて，環境構築．
1. 「最新の」`develop` から `feature/add-rule-names` みたいなブランチを切る（develop を最新版にしておかないと，いらぬ conflict してめんどくさくなる可能性がある）．`git checkout -b feature/add-rule-names` みたいにすれば良い．ブランチを切った後は `git branch` でブランチ一覧（と今いるブランチ）を確認すると良い．
2. 実装する．今回は https://github.com/lmntal/slim/blob/develop/lib/system_ruleset.lmn にルール名を付加するだけ．実装が終わったら，`git status` で何が変更されているか（余計なファイルをいじっていないか）確認する．`git diff` もおすすめ．
3. `git add 変更したファイル` する．また `git status` すると良い．
4. `git commit -m "何をやったか短く書く"` する．また `git status` すると良い．
5. `git push --set-upstream origin 今のブランチ` する．まぁ，`git push` とだけやって，警告で出てくるやつをコピペするので良いと思う（ぼくは雑な人間なのでいつもそんな感じ）．権限が足りないと出たら教えてください（権限をあげます）．
6. github の方（web page）から pull request をする．右側に assignees とか reviewer とかあると思うので，ぼくと山本さんらへんを指定しておくと吉です．マージは（一応）まだしないでください．
7. slack で pull request した旨，教えてください🙇‍♀️

何かわからないこと（怪しげなこと）があったら，気軽に教えてください．

**Comment by imaren** [comment]
add-system_rule-names #275

pull request 出しました！
