### ISSUE TITLE
nlmemに関するバグ

### ISSUE THREAD

**Issue by kyawaway** [lmntal/slim#316]
以下のコードで再現可能：

``` 
{
 system_ruleset.
 inner@@ {s,$g[]} :- nlmem.kill({v,$g[]},trash).
 
 outer@@ {t,$g[]} :- {u,$g[]}.
 }.
 
 {{s},t. }.
```

入れ子の膜があり，内側にnlmemに反応する要素，外側に任意のルールが反応する要素があり，どちらを先に反応させても最終的に状態が合流するような構造を書いた時，

nlmemのルール(inner)を先に反応させると，nlmemが反応した膜を内側に持つ膜がルール(outer)に反応しなくなる．

生成される状態空間：

<img width="542" alt="20231113bug1" src="https://github.com/lmntal/slim/assets/33660146/5d4f30bb-7682-4cb5-8721-f37eda56801e">

本来は状態は合流する．

**Comment by kyawaway** [comment]
尚，膜内に

```
nlmem_kill@@
kill(M, T) :- unary(T) | '$callback'('nlmem_kill', M, T).
```

を記述すると，正常に動作する：

```
{
system_ruleset.
inner@@ {s,$g[]} :- kill({v,$g[]},trash).

outer@@ {t,$g[]} :- {u,$g[]}.

nlmem_kill@@
kill(M, T) :- unary(T) | '$callback'('nlmem_kill', M, T).
}.
 
{{s},t. }.
```

状態空間：
<img width="509" alt="20231113bug2" src="https://github.com/lmntal/slim/assets/33660146/ca1ff0d5-58ba-4791-bee4-9383e8422e3a">

**Comment by tuesdayjz** [comment]
```
{
   system_ruleset.
   inner@@ {s,$g[]} :- nlmem.kill({v,$g[]},trash).
   outer@@ {t,$g[]} :- {u,$g[]}.
 }.
 {{s},t. }.
```
- 指摘：outer -> inner は適用できるのに、innerを適用した後にouterが適用できない
- 結論：バグではない
- 解説：
  - innerの適用の際に、膜内にnlmemのためのルールセットが追加される
  - outerのヘッドの膜内にはルール文脈がないため、outerはルールが含まれていない膜とマッチする
  - innerの適用後は膜内にnlmemのルールセットが存在するため、outerはマッチしない
- 解決法：`outer@@ {t,$g[],@r} :- {u,$g[],@r}.` と書けばマッチする。
- system_rulesetを使わない再現例：
```
rule1@@ {{s,$p[]},$q} :- {nlmem.kill({v,$p[]},trash),$q}. // {s}を削除するルール
rule2@@ {t,$q} :- {u,$q}. // tをuに変えるルール
{{s},t}.
```
