### ISSUE TITLE
シングルクオートを含むアトム名を認識しない

### ISSUE THREAD

**Issue by avtomat2023** [lmntal/slim#34]
以下のプログラムをコンパイルすると

```
'a''b'.
```

以下の命令を含む中間コードが生成される。

```
        newatom      [1, 0, 'a\'b'_0]
```

実行すると、エスケープされたシングルクオートを認識できず、slimが異常終了する。

**Comment by ayhsmt97** [comment]
現行の SLIM で当該プログラムを実行したところ、
`unknown instruction name b`
と出力された

**Comment by k-ueda** [comment]
loader/il_lexer.cpp.reの120行目の
` sstr = "'"  [^']* "'"; `
が，エスケープされたシングルクォートを読み飛ばしてくれないのが原因ですね．（cf. 121行目の dstr は対策済）
