### ISSUE TITLE
bug at unifying two links

### ISSUE THREAD

**Issue by alim428** [lmntal/slim#38]
(1) the problem
There is a bug in slim which procedures corrupted graph.
To see it, please run the following program.

```
  init:-a(B,!R),b(B,!R).
  rm@@ a(B,R):-R=B.
```

with "--show-hl" option, you can see atom 'a' still exist.

```
   == HyperLink =============================================================
    [hl_ID]  [parent] [linked with] [num] [direct children ( inside info )]
         4      root            b             2            7.
         7         4             a             2
```

The result is "b(!B,!B)".  but this graph is corrupted. 
when unifying '!B' and 'R' links,  '!B' did not set to point to atom 'b', so it is still pointing to the already deleted atom 'a'.
As a result, trying to traverse the resulted graph, obtained from running above program, encounters 'segmentation fault'.

(2) solution.
 Let hyperlink point to the atom, for example, let '!B' point to 'b' atom in above example.
 In "lmn_mem_unify_atom_args" function in 'membrane.c' do the following.
At the second branch of 'if-else' statement, add the following

```
 LMN_SATOM_SET_LINK(ap1, 0, ap2);
 LMN_SATOM_SET_ATTR(ap1, 0, attr2);
```

At the third branch of 'if-else' statement, add the following

```
 LMN_SATOM_SET_LINK(ap2, 0, ap1);
 LMN_SATOM_SET_ATTR(ap2, 0, attr1);
```

Done.

I have tested this and it worked.

Best Regards,
Alimjan Yasin

**Comment by k-ueda** [comment]
This bug seems to have been fixed years before.

**Comment by alim428** [comment]
*   This bug seems to have been fixed years before.

      Yes, there was a bug of unifying hyperlinks, and it was fixed.
      Now I totally forget its details.
________________________________
