### ISSUE TITLE
atomic ruleset (atomic all) のバグ[2.2.2]

### ISSUE THREAD

**Issue by k-akaike** [lmntal/slim#9]
## 現象

atomic ruleset のモードを1にすると、セグメンテーション違反になる

```
{
 '$callback'('atomic_ruleset', 1).
 a :- b.
 b :- c.
 b :- d.
}.

a.
```

slimの2.2.2(rev.486)ではバグが起き、2.2.0(rev.464)ではおきないことは確認しました。

**Comment by nikosai** [comment]
atomic_ruleset自体が廃止済み機能のためcloseします (see #325)
